[project]
name = "test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=2.19.1",
    "faiss-cpu>=1.15.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "requests>=2.28.1",
    "scikit-learn>=1.9.1",
    "scipy>=1.17.1",
    "sentence-transformers>=6.1.0",
    "torch>=2.14.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu126"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
